require:
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - Rakefile
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/devise.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - config/initializers/permissions_policy.rb
    - config/puma.rb
    - lib/tasks/auto_annotate_models.rake

Metrics/AbcSize:
  Exclude:
    - db/migrate/20230406141125_devise_create_users.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/20230406141125_devise_create_users.rb
    - db/migrate/20230408121228_devise_invitable_add_to_users.rb
    - db/migrate/20230409121350_devise_create_admins.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
